<a href="https://colab.research.google.com/github/MorganDiaz2513892022/datawarehouse-seguros/blob/main/notebook/Siniestros.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://raw.githubusercontent.com/MorganDiaz2513892022/datawarehouse-seguros/refs/heads/main/data/siniestros.csv

In [4]:
import pandas as pd

In [5]:
url_siniestros = "https://raw.githubusercontent.com/MorganDiaz2513892022/datawarehouse-seguros/refs/heads/main/data/siniestros.csv"
df = pd.read_csv(url_siniestros)
df.head()

   id_siniestro  id_poliza fecha_siniestro monto_siniestro     estado
0             1      17400      16-10-2025         2092.59    ABIERTO
1             2       2465      01/08/2025        7,076.25    Abierto
2             3      15785      19-09-2025         702.27     cerrado
3             4      14299      27/09/2025         274.63     Abierto
4             5      12908      01/12/2025        9,377.69  Rechazado

In [6]:
#exploracion de datos
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4620 entries, 0 to 4619
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_siniestro     4620 non-null   int64
 1   id_poliza        4620 non-null   int64
 2   fecha_siniestro  4620 non-null   object
 3   monto_siniestro  4004 non-null   object
 4   estado           3322 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.6+ KB

id_siniestro          0
id_poliza             0
fecha_siniestro       0
monto_siniestro     616
estado             1298
dtype: int64

In [7]:
#limpieza general de datos
def limpiar_dataframe(df):

    df.columns = df.columns.str.strip().str.lower()

    for col in df.select_dtypes(include='object').columns:
        df[col] = df[col].astype(str).str.strip()

    df = df.replace(r'^\s*$', pd.NA, regex=True)

    df = df.drop_duplicates()

    return df

In [14]:
import pandas as pd

# 1. CARGAR DATOS
url_siniestros = "https://raw.githubusercontent.com/MorganDiaz2513892022/datawarehouse-seguros/refs/heads/main/data/siniestros.csv"
siniestros = pd.read_csv(url_siniestros)

# 2. LIMPIAR
siniestros = limpiar_dataframe(siniestros)

# 3. TRANSFORMAR
siniestros['fecha_siniestro'] = pd.to_datetime(
    siniestros['fecha_siniestro'], errors='coerce'
)

# 4. VERIFICAR
print(siniestros.head())

   id_siniestro  id_poliza fecha_siniestro monto_siniestro     estado
0             1      17400      2025-10-16         2092.59    ABIERTO
1             2       2465             NaT        7,076.25    Abierto
2             3      15785      2025-09-19          702.27    cerrado
3             4      14299             NaT          274.63    Abierto
4             5      12908             NaT        9,377.69  Rechazado

/tmp/ipykernel_16435/1076624037.py:11: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  siniestros['fecha_siniestro'] = pd.to_datetime(

In [16]:
#exportacion de archivos curated
siniestros.to_csv("siniestros_curated.csv", index=False)

In [21]:
#conectar python con postgreSQL
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine

engine = create_engine(
"postgresql://etl_morgan:obz3aYhwV9mgtsMvuYckNzaEEIh9z7w9@dpg-d6v9fjkr85hc73b7s7p0-a.oregon-postgres.render.com/etl_siniestros"
)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Requirement already satisfied: psycopg2-binary in /usr/local/lib/python3.12/dist-packages (2.9.11)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)

In [22]:
siniestros.to_sql('siniestros', engine, if_exists='append', index=False)

620

In [24]:
#consulta de sql
import pandas as pd

consulta = """
SELECT estado, COUNT(*) AS total
FROM siniestros
GROUP BY estado;
"""

resultado = pd.read_sql(consulta, engine)
print(resultado)

      estado  total
0  Rechazado    636
1    Cerrado    645
2        nan   1298
3    ABIERTO    664
4    cerrado    677
5    Abierto    700